name: Releases

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: "build"
        run: |
          npm i pnpm -g
          pnpm i
          pnpm run build
          pnpm run test:run

      - name: "create dist"
        run: |
          mkdir ./dist/scripts/mpv-easy-config/rs-ext -p

          cp ./mpv-easy/es5/mpv-easy-es5.js ./dist/scripts/mpv-easy-es5.js
          cp -r ./mpv-easy/fonts ./dist
          cp -r ./mpv-anime4k/shaders ./dist
          cp ./mpv-easy/mpv-conf/mpv.conf ./dist/mpv.conf

          chmod 777 ./rs-ext/*

          cp -r ./dist ./mpy-easy-macos
          cp -r ./dist ./mpy-easy-linux
          cp -r ./dist ./mpy-easy-android
          cp -r ./dist ./mpy-easy-windows
          cp -r ./dist ./mpy-easy-deno-windows
          cp -r ./dist ./mpy-easy-qjs-windows
          cp -r ./dist ./mpy-easy-boa-windows

          cp ./rs-ext/rs-ext-macos ./mpy-easy-macos/scripts/mpv-easy-config/rs-ext/rs-ext-macos
          cp ./rs-ext/rs-ext-ubuntu ./mpy-easy-linux/scripts/mpv-easy-config/rs-ext/rs-ext-linux
          cp ./rs-ext/rs-ext-android ./mpy-easy-android/scripts/mpv-easy-config/rs-ext/rs-ext-android
          cp ./rs-ext/rs-ext-windows ./mpy-easy-windows/scripts/mpv-easy-config/rs-ext/rs-ext-windows
          cp ./rs-ext/rs-ext-windows ./mpy-easy-deno-windows/scripts/mpv-easy-config/rs-ext/rs-ext-windows
          cp ./rs-ext/rs-ext-windows ./mpy-easy-qjs-windows/scripts/mpv-easy-config/rs-ext/rs-ext-windows
          cp ./rs-ext/rs-ext-windows ./mpy-easy-boa-windows/scripts/mpv-easy-config/rs-ext/rs-ext-windows

          cp ./deno-dll/mpv-deno-windows.dll ./mpy-easy-deno-windows/scripts/mpv-deno-windows.dll
          rm ./mpy-easy-deno-windows/scripts/mpv-easy-es5.js
          mkdir ./mpy-easy-deno-windows/scripts-deno
          cp ./mpv-easy/bundle/mpv-easy-es6.js ./mpy-easy-deno-windows/scripts-deno/mpv-easy-es6.js
          mv ./mpy-easy-deno-windows/scripts/mpv-easy-config ./mpy-easy-deno-windows/scripts-deno/mpv-easy-config


          cp ./qjs-dll/mpv-qjs-windows.dll ./mpy-easy-qjs-windows/scripts/mpv-qjs-windows.dll
          rm ./mpy-easy-qjs-windows/scripts/mpv-easy-es5.js
          mkdir ./mpy-easy-qjs-windows/scripts-qjs
          cp ./mpv-easy/bundle/mpv-easy-es6.js ./mpy-easy-qjs-windows/scripts-qjs/mpv-easy-es6.js
          mv ./mpy-easy-qjs-windows/scripts/mpv-easy-config ./mpy-easy-qjs-windows/scripts-qjs/mpv-easy-config

          cp ./boa-dll/mpv-boa-windows.dll ./mpy-easy-boa-windows/scripts/mpv-boa-windows.dll
          rm ./mpy-easy-boa-windows/scripts/mpv-easy-es5.js
          mkdir ./mpy-easy-boa-windows/scripts-boa
          cp ./mpv-easy/bundle/mpv-easy-es6.js ./mpy-easy-boa-windows/scripts-boa/mpv-easy-es6.js
          mv ./mpy-easy-boa-windows/scripts/mpv-easy-config ./mpy-easy-boa-windows/scripts-boa/mpv-easy-config

          cd ./mpy-easy-macos
          zip -r -q ./mpy-easy-macos.zip .
          cd ..

          cd ./mpy-easy-linux
          zip -r -q ./mpy-easy-linux.zip .
          cd ..

          cd ./mpy-easy-android
          zip -r -q ./mpy-easy-android.zip .
          cd ..

          cd ./mpy-easy-windows
          zip -r -q ./mpy-easy-windows.zip .
          cd ..

          cd ./mpy-easy-deno-windows
          zip -r -q ./mpy-easy-deno-windows.zip .
          cd ..

          cd ./mpy-easy-qjs-windows
          zip -r -q ./mpy-easy-qjs-windows.zip .
          cd ..

          cd ./mpy-easy-boa-windows
          zip -r -q ./mpy-easy-boa-windows.zip .
          cd ..
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./mpy-easy-*/*.zip"
