name: Releases

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-A warnings"
          toolchain: "nightly"
      - name: "build"
        run: |
          cargo install wasm-pack

          npm i pnpm -g
          pnpm i
          pnpm run build
          pnpm run test:run
